### ISSUE TITLE
pEqn.H and mesh motion in MPPICInterDyMFoam.C

### ISSUE THREAD

**Issue by skyopener** [TonkomoLLC/MPPICInterDyMFoam#1]
Thanks for your kind effort on releasing so many great solvers of openfoam on github. 
Recently, I went through the details of MPPICInterDyMFoam, and found that:
1: MPPICInterDyMFoam/MPPCInterDyMFoam/pEqn.H
The calculation of the pressure equation does not consider the presence of solid phase, i.e., the solid concentration should be considered. Now, the pressure equation of this version is exactly transferred from the PEqn.H of InterFoam of openfoam version 1706. For adding the dynamic mesh, this should be similar to the MPPICInterFoam released.
2: Before the mesh update, the coordinate of the kinetic cloud should be saved (due to the special tracking algorithm of solid phase in the openfoam framework). Details can be found in DPMFoam, SparyFoam.
Now, the DPMFoam, MPPICFoam, InterFoam were released in the openfoam 2012, with the addition of dynamic mesh function. Meanwhile, the previous tracking algorithm of solid phase with dynamic mesh has some problems when the particle hits the AMI surface, which has also been solved in the openfoam 2012.

**Comment by TonkomoLLC** [comment]
Hello, thanks for the great feedback. I apologize for my delayed reply.

I really appreciate the review of the code: I agree with your points.

Please see the `OF-v2106` branch. The tutorial runs to ~0.160 seconds and then it starts to have problems. However, I am not sure if there is a a problem with the solver or the tutorial. 

Thanks for kindly reviewing the updates I have posted. If all is good, I'll remove the files in the `master` and `v1706` branches and replace with the `v2106` branch. I don't plan to maintain code for v1606+ or v1706.

Thanks so much.

Best regards,

Eric

**Comment by TonkomoLLC** [comment]
Thank you @skyopener for the fixes! All changes are merged into the master branch.
